### ISSUE TITLE
Implement a node command line tool

### ISSUE THREAD

**Issue by vccortez** [takuyaa/waifu2x-js#1]
I believe that implementing this as a command line utility would greatly improve the usefulness and popularity of this module.

**Comment by preco21** [comment]
I agree. `npm` would make easier to install a module.

**Comment by preco21** [comment]
Cool! now it's available in `npm`! https://www.npmjs.com/package/waifu2x-js

**Comment by vccortez** [comment]
Nice! Closing this issue then.
